FROM google/cloud-sdk:slim

COPY --from=hashicorp/terraform:light /bin/terraform /bin
COPY --from=hashicorp/packer:light /bin/packer /bin

RUN apt install -y man vim git bash
RUN groupadd -g 1000 user
RUN useradd --shell /bin/bash user -d /home/user -u 1000 -g 1000 -m

#&& echo 'user ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER user

WORKDIR /home/user/

COPY .ssh /home/user/.ssh
COPY credentials.json/ /home/user
COPY docker-compose.yml/ /home/user
COPY Dockerfile/ /home/user
COPY main.tf/ /home/user
COPY LICENSE/ /home/user
COPY universal-application-tool-0.0.1/ /home/user/universal-application-tool-0.0.1/

CMD bash
