# Use postgres/example user/passwordcredentials
version: '3.1'

services:

  localstack:
    image: localstack/localstack
    container_name: localstack-test
    ports:
      - 6645:4566
    environment:
      - SERVICES=s3,ses

  db:
    image: postgres:12.5
    restart: always
    container_name: postgres-test
    ports:
      - 2345:5432
    environment:
      POSTGRES_PASSWORD: example

  fake-idcs:
    image: public.ecr.aws/t1q6b4h2/oidc-provider:latest
    restart: always
    container_name: fake-idcs
    ports:
      - 8033:3380

  civiform:
    image: civiform
    restart: always
    container_name: civiform-test
    links:
      - "db:database"
      - "fake-idcs"
    ports:
      - 9999:9000
      - 9998:9001
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION
      - AWS_SES_SENDER
      - AWS_S3_BUCKET_NAME
      - IDCS_CLIENT_ID=foo
      - IDCS_SECRET=bar
      - IDCS_DISCOVERY_URI=http://fake-idcs:3380/.well-known/openid-configuration
      - ADFS_CLIENT_ID
      - ADFS_SECRET
      - DB_JDBC_STRING=jdbc:postgresql://database:5432/postgres
      - BASE_URL=https://civiform:9000
      - CF_OPTIONAL_QUESTIONS

    command: ~run -Dhttps.port=9000 -Dhttp.port=9001 -Dconfig.file=conf/application.dev.conf
